version: '3.4'

services:
  api:
    image: test2
    build:
      context: .
      dockerfile: SoftPlanTest2/API/Dockerfile
    ports:
      - 80
      - 5000
  api2:
    image: test1
    build:
      context: .
      dockerfile: SoftplanTest1/API/Dockerfile
    ports:
      - 81
      - 3000
      