# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - 80
      - 3000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ~/.vsdbg:c:\remote_debugger:rw
